# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orama < Formula
  desc "CLI tool for the Orama decentralized network"
  homepage "https://github.com/DeBrosDAO/orama"
  version "0.122.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DeBrosDAO/orama/releases/download/v0.122.10/orama_0.122.10_darwin_amd64.tar.gz"
      sha256 "7434da87b35a1eb1851d09796e9c54210b683aa925e2d587dbd05ef020eccd90"

      define_method(:install) do
        bin.install "orama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DeBrosDAO/orama/releases/download/v0.122.10/orama_0.122.10_darwin_arm64.tar.gz"
      sha256 "20503196828ecdb8c123b2c08d30943937f799aee0a799ef30415d6cbbfbf106"

      define_method(:install) do
        bin.install "orama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DeBrosDAO/orama/releases/download/v0.122.10/orama_0.122.10_linux_amd64.tar.gz"
      sha256 "66ac5a7e4950710e9be29ee1d30bba12ffc51086a20c3d987028df8393ba72e3"
      define_method(:install) do
        bin.install "orama"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DeBrosDAO/orama/releases/download/v0.122.10/orama_0.122.10_linux_arm64.tar.gz"
      sha256 "8b3087271cdc3ace36c5418767ddee0cabd190c23290bc032b376b233ca6de03"
      define_method(:install) do
        bin.install "orama"
      end
    end
  end

  test do
    system "#{bin}/orama", "--version"
  end
end
