# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Rootwallet < Formula
  desc "RootWallet CLI — terminal wallet for EVM and Solana"
  homepage "https://rootwallet.io"
  url "https://registry.npmjs.org/@debros/root-cli/-/root-cli-0.181.1.tgz"
  sha256 "22af6b1374b808cd32f1e160f5d324fee40668363119f4bd40882dcf9e9dd882"
  version "0.181.1"
  license "MIT"

  depends_on "node"

  def install
    # dist/index.js is fully bundled (tsup noExternal) with a node
    # shebang, so no npm install / node_modules is needed.
    libexec.install "dist", "package.json"
    (libexec/"dist/index.js").chmod 0755
    bin.install_symlink libexec/"dist/index.js" => "rw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rw --version")
  end
end
