# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Rootwallet < Formula
  desc "RootWallet CLI — terminal wallet for EVM and Solana"
  homepage "https://rootwallet.io"
  version "0.107.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.0/rootwallet_0.107.0_darwin-arm64.tar.gz"
      sha256 "fd042c6d0ec1b2c5c0961a7dbe28d7ac79954cb4c994f4d10c669dc362996de4"
    else
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.0/rootwallet_0.107.0_darwin-amd64.tar.gz"
      sha256 "351aaec20731d6fe802c11e07552bce44a9622f8f20cf1603a69308329cacbc5"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.0/rootwallet_0.107.0_linux-arm64.tar.gz"
      sha256 "477c846e46c4938c25c74bc50621eb74a7d69eb200d71f6a11ce9c02244e083a"
    else
      url "https://github.com/DeBrosDAO/rootwallet/releases/download/v0.107.0/rootwallet_0.107.0_linux-amd64.tar.gz"
      sha256 "1151e300a806b9e879a99c7d506ea167ef09fd7ac18ea0be4e6ab7eb335e6a04"
    end
  end

  def install
    bin.install "rw"
  end

  test do
    system "#{bin}/rw", "--version"
  end
end
